# Generated by Django 4.1.7 on 2023-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='burn_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время горения'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='size',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размеры'),
        ),
    ]
