# Generated by Django 4.1.7 on 2023-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
    ]
