# Generated by Django 4.1.7 on 2023-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0002_alter_reviews_content_alter_reviews_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
    ]
