# Generated by Django 4.1.7 on 2023-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0003_remove_reviews_slug_alter_reviews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
