# Generated by Django 4.1.7 on 2023-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle', '0005_category_alter_reviews_title_candle_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Таблица товаров', 'verbose_name_plural': 'Таблица товаров'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
